name: Testing

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]
  # manually start testing.
  workflow_dispatch:

jobs:

  tests:
    name: Test on go ${{ matrix.go_version }}
    strategy:
      matrix:
        go_version: [
          "1.19",
          "1.20",
          "1.21",
        ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go_version }}

    - name: Test
      run: bash scripts/run_all_tests.sh

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
